language: elixir

sudo: false

elixir:
  - 1.4.5

otp_release:
  - 19.3
  - 20.0

before_script:
  - mix local.hex --force
  - mix deps.get --only test

script: mix test

after_script:
  - MIX_ENV=docs mix deps.get